image: python:3.12.4

stages:
  - test
  - security
  - deploy

.build-env: &build-env
  - pip install uv
  - uv sync --index https://gitlab-ci-token:$INTERNAL_REGISTRY_TOKEN@$INTERNAL_REG_URL_SHORT

pipeline_status_dummy:
  stage: test
  script:
    - echo "this job is to prevent a spinning status wheel in the pipeline status on merge request events with no trigger."
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'


bandit_scan:
  stage: security
  script:
    - *build-env
    - uv run bandit -c pyproject.toml -r src/ -f xml -o bandit-report.xml
  artifacts:
    when: always
    paths:
      - bandit-report.xml
    reports:
      junit: bandit-report.xml
  rules:
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ "/^development.*$/"'
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ "/^stable.*$/"'
  - if: '$CI_COMMIT_REF_NAME =~ "/^development.*$/" || $CI_COMMIT_REF_NAME =~ "/^stable.*$/"'
  - if: $CI_PIPELINE_SOURCE == "schedule" # Runs automatically on schedule
  allow_failure: True

pip_audit_scan:
  stage: security
  script:
    # Generates a CycloneDX SBOM including found vulnerabilities
    - *build-env
    - uv run pip-audit -f cyclonedx-xml -o gl-sbom-python.cdx.xml
  artifacts:
    name: "pip-audit-security-report"
    when: always
    expire_in: 1 week
    paths:
      - gl-sbom-python.cdx.xml
    reports:
      # This exposes the data directly into GitLab's dependency scanner UI
      junit: gl-sbom-python.cdx.xml
  # Allow the pipeline to pass even if vulnerabilities are found (Optional)
  # Remove the line below if you want failing audits to break your build
  allow_failure: True
  rules:
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ "/^development.*$/"'
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ "/^stable.*$/"'
  - if: '$CI_COMMIT_REF_NAME =~ "/^development.*$/" || $CI_COMMIT_REF_NAME =~ "/^stable.*$/"'
  - if: $CI_PIPELINE_SOURCE == "schedule" # Runs automatically on schedule

unit_test:
  stage: test
  script:
  - *build-env
  - chmod +x ./tools/test.sh
  - ./tools/test.sh
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    when: always
    reports:
      junit: tests/report.xml
  rules:
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ "/^development.*$/"'
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ "/^stable.*$/"'
  - if: '$CI_COMMIT_REF_NAME =~ "/^development.*$/" || $CI_COMMIT_REF_NAME =~ "/^stable.*$/"'

docbuild_test:
  stage: test
  script:
  - *build-env
  - chmod +x ./tools/docs.sh
  - ./tools/docs.sh html-ci
  rules:
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ "/^development.*$/"'
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ "/^stable.*$/"'
  - if: '$CI_COMMIT_REF_NAME =~ "/^development.*$/" || $CI_COMMIT_REF_NAME =~ "/^stable.*$/"'



pages:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
  script:
  - *build-env
  # this fetches the remote and tracks all the origin branches
  # as locals so that sphinx multiversion can recognize them
  - git fetch --all
  - git branch -r | grep -v '\->' | while read remote; do git branch --track "${remote#origin/}" "$remote"; done
  - chmod +x ./tools/docs.sh
  - ./tools/docs.sh html-multiversioned-ci
  # UNCOMMENT THIS BLOCK WHEN IPAGES REPO IS READY
  #clone the ipages repo on github
  - git clone https://oauth2:$NIST_IPAGES_TOKEN@github.com/usnistgov/rminstr-specs-ipages.git nist-pages
  - git config --global user.email "daniel.c.gray@nist.gov"
  - git config --global user.name "d-c-gray"
  # removes any subdirectories in the
  # i-pages repo, those are build files.
  - rm -rf nist-pages/*/
  - cp -R public/* nist-pages
  # move to the cloned folder
  - cd nist-pages
  - touch .nojekyll
  - git add .
  - git diff-index --quiet HEAD || git commit -m "updating docs - automated"
  - git push
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" # Runs automatically on schedule




project-package-registry:
  stage: deploy
  image: python:latest
  variables:
    TWINE_USERNAME: gitlab-ci-token
    TWINE_PASSWORD: $CI_JOB_TOKEN
  script:
    - pip install uv
    - pip install twine
    - uv build
    - python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/* --verbose
  rules:
    - if: $CI_COMMIT_TAG

internal-package-registry:
  stage: deploy
  image: python:latest
  variables:
    TWINE_USERNAME: $INTERNAL_REGISTRY_TOKEN_NAME
    TWINE_PASSWORD: $INTERNAL_REGISTRY_TOKEN
  script:
    - pip install uv
    - pip install twine
    - uv build
    - python -m twine upload --repository-url ${CI_API_V4_URL}/projects/10154/packages/pypi dist/* --verbose
  rules:
    - if: $CI_COMMIT_TAG

pypi-release:
  stage: deploy
  image: python:latest
  variables:
  script:
    - pip install uv
    - uv build
    - uv publish --token $PYPI_TOKEN
  rules:
    - if: $CI_COMMIT_TAG
